development:
  dialect: sqlite3
  datasource: .dbdata/db.sqlite
  dir: /Users/selmison/Projects/code-micro-videos/backend/migrations

test:
  dialect: sqlite3
  datasource: file::memory:?cache=shared
  dir: /Users/selmison/Projects/code-micro-videos/backend/migrations

production:
  dialect: postgres
  datasource: host=db dbname=code-micro-videos user=${DB_USER} password=${DB_PASSWORD} sslmode=required
  dir: migrations/postgres
  table: migrations